server:
  port: 8080 # Puerto principal por donde entrarán todas las peticiones al sistema

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          # Activa la creación dinámica de rutas usando Eureka
          lower-case-service-id: true # Convierte los nombres de los microservicios a minúsculas en la URL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Apunta al Eureka Server que creamos antes
  instance:
    prefer-ip-address: true